<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>itemDropdown</name>
   <tag></tag>
   <elementGuidId>0fba737c-73fb-49a2-a41a-d3a1e4375eae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select//child::option</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
